// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk5Iq_wXW5Tt_tUkPyNUsygoQr5weJhx0',
    appId: '1:108859930111:web:70c955a590c0d8c68de3ca',
    messagingSenderId: '108859930111',
    projectId: 'mysakhi-app',
    authDomain: 'mysakhi-app.firebaseapp.com',
    databaseURL: 'https://mysakhi-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mysakhi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa_qLJ1oYR1KncV7XLjzUOM2SXH3101ho',
    appId: '1:108859930111:android:5e50759be3c65bf08de3ca',
    messagingSenderId: '108859930111',
    projectId: 'mysakhi-app',
    databaseURL: 'https://mysakhi-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mysakhi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYz07aCRAGDCe23e_5ykGQm53aX6ZHyo',
    appId: '1:108859930111:ios:aeccfa3dbde3956d8de3ca',
    messagingSenderId: '108859930111',
    projectId: 'mysakhi-app',
    databaseURL: 'https://mysakhi-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mysakhi-app.firebasestorage.app',
    iosBundleId: 'com.mysakhi.mysakhiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYz07aCRAGDCe23e_5ykGQm53aX6ZHyo',
    appId: '1:108859930111:ios:aeccfa3dbde3956d8de3ca',
    messagingSenderId: '108859930111',
    projectId: 'mysakhi-app',
    databaseURL: 'https://mysakhi-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mysakhi-app.firebasestorage.app',
    iosBundleId: 'com.mysakhi.mysakhiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk5Iq_wXW5Tt_tUkPyNUsygoQr5weJhx0',
    appId: '1:108859930111:web:f3afe06b4f4342718de3ca',
    messagingSenderId: '108859930111',
    projectId: 'mysakhi-app',
    authDomain: 'mysakhi-app.firebaseapp.com',
    databaseURL: 'https://mysakhi-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mysakhi-app.firebasestorage.app',
  );
}
